# Generated by Django 5.1.4 on 2025-05-08 16:21

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CombinedReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_debut', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 8))])),
                ('date_fin', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.appartement')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicule')),
            ],
        ),
    ]
