# Generated by Django 5.1.4 on 2025-06-10 21:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_message_combinedreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedreservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 10))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 10))]),
        ),
    ]
