# Generated by Django 5.1.4 on 2025-06-21 10:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_combinedreservation_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedreservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 21))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 21))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
