# Generated by Django 5.1.4 on 2025-06-23 11:50

import cloudinary.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_combinedreservation_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='combinedreservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 23))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 23))]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
